KOMTEK_WEB/ViewModels/SolveVM.cs
using System.ComponentModel.DataAnnotations;

namespace KOMTEK_WEB.ViewModels
{
    public class SolveVM
    {
        [MinLength(1)]
        public string Expression { get; set; }

        public string Result { get; set; }
    }
}

KOMTEK_WEB/Controllers/API/CalculatorController.cs
using Managed_Wrappers.Managed;
using Microsoft.AspNetCore.Mvc;


namespace KOMTEK_WEB.Controllers.API
{
    [Route("api/[controller]")]
    [ApiController]
    public class CalculatorController : ControllerBase
    {

        [HttpGet]
        public ActionResult<string> Get(string expression)
        {
            if (string.IsNullOrWhiteSpace(expression))
            {
                return BadRequest();
            }

            try
            {
                return CalcWrapper.Solve(expression, out double result)
                    ? result.ToString()
                    : CalcWrapper.GetLastError();
            }
            catch
            {
                return "The expression is not recognized.";
            }
        }
    }
}

KOMTEK_WEB/Controllers/SolverController.cs
using KOMTEK_WEB.Middleware;
using KOMTEK_WEB.ViewModels;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Net.Http;
using System.Threading.Tasks;

namespace KOMTEK_WEB.Controllers
{
    public class SolverController : Controller
    {
        private readonly IHttpClientFactory _clientFactory;

        private static string HttpRoute = "";
        private readonly string Controller = nameof(API.CalculatorController)
            .Replace("Controller", string.Empty);

        private Uri BaseAdress => new Uri(AppEnvironment.BaseUrl);

        public SolverController(IHttpClientFactory clientFactory)
        {
            _clientFactory = clientFactory;
        }

        [HttpGet]
        public async Task<ActionResult<SolveVM>> Solve(string expression)
        {
            if (string.IsNullOrWhiteSpace(expression))
            {
                return View();
            }

            var solve = new SolveVM
            {
                Expression = expression
            };

            HttpClient client = _clientFactory.CreateClient();
            client.BaseAddress = BaseAdress;
            string url = Url.RouteUrl("DefaultApi", new { HttpRoute, Controller, expression });
            HttpResponseMessage response = await client.GetAsync(url);

            if (response.StatusCode != System.Net.HttpStatusCode.OK)
            {
                return StatusCode((int)response.StatusCode);
            }

            solve.Result = await response.Content.ReadAsStringAsync();

            return View(solve);
        }
    }
}

KOMTEK_WEB/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Komtek</title>
    <environment include="Development">
        <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css" />
        <link rel="stylesheet" href="~/css/site.css" />
    </environment>
    <environment exclude="Development">
        <link rel="stylesheet" href="https://ajax.aspnetcdn.com/ajax/bootstrap/3.3.7/css/bootstrap.min.css"
              asp-fallback-href="~/lib/bootstrap/dist/css/bootstrap.min.css"
              asp-fallback-test-class="sr-only" asp-fallback-test-property="position" asp-fallback-test-value="absolute" />
        <link rel="stylesheet" href="~/css/site.min.css" asp-append-version="true" />
    </environment>
</head>
<body>
    <nav class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a asp-controller="Solver" asp-action="Solve" class="navbar-brand">Komtek</a>
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav"></ul>
            </div>
        </div>
    </nav>
    <div class="container">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @System.DateTime.Now.Year - Komtek</p>
        </footer>
    </div>
    <environment include="Development">
        <script src="~/lib/jquery/dist/jquery.js"></script>
        <script src="~/lib/bootstrap/dist/js/bootstrap.js"></script>
    </environment>
    <environment exclude="Development">
        <script src="https://ajax.aspnetcdn.com/ajax/jquery/jquery-2.2.0.min.js"
                asp-fallback-src="~/lib/jquery/dist/jquery.min.js"
                asp-fallback-test="window.jQuery"
                crossorigin="anonymous"
                integrity="sha384-K+ctZQ+LL8q6tP7I94W+qzQsfRV2a+AfHIi9k8z8l9ggpc8X+Ytst4yBo/hH+8Fk">
        </script>
        <script src="https://ajax.aspnetcdn.com/ajax/bootstrap/3.3.7/bootstrap.min.js"
                asp-fallback-src="~/lib/bootstrap/dist/js/bootstrap.min.js"
                asp-fallback-test="window.jQuery && window.jQuery.fn && window.jQuery.fn.modal"
                crossorigin="anonymous"
                integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa">
        </script>
    </environment>
    @await RenderSectionAsync("Scripts", false)
</body>
</html>

KOMTEK_WEB/Views/Solver/Solve.cshtml
@model SolveVM
@{
    ViewData["Title"] = "Solve";
}

<h2>@ViewData["Title"]</h2>
<div class="row">
    <div class="col-md-4">
        <form asp-action="Solve" method="get">
            <div class="form-group">
                <label asp-for="Expression" class="control-label"></label>
                <textarea asp-for="Expression" class="form-control"></textarea>
            </div>
            <div class="form-group">
                <label asp-for="Result" class="control-label"></label>
                <textarea asp-for="Result" class="form-control" disabled="disabled" readonly="readonly"></textarea>
            </div>
            <div class="form-group">
                <button type="submit" class="btn btn-primary">Solve</button>
            </div>
        </form>
    </div>
</div>

@section Scripts {
    @{ await Html.RenderPartialAsync("_ValidationScriptsPartial"); }
}